#PATH_DRIVE_PASSWORD: 'XXXXXXXXX'
#HPC_DRIVE_PASSWORD: 'XXXXXXXXXX'
#
#NOTE: all variables should not have any space at the begining
#this will impact when calling in .sh scripts
#

CONFIG_TOKENS_FILE: 'config.tokens.yaml'
TABLE_NAME_PROD: 'gatorseq_processing_prod'
TABLE_NAME: 'gatorseq_processing'

DEV_MYSQL_HOST: 'mysql09c.ahc.ufl.edu'
DEV_MYSQL_USERNAME: 'com_path_imm_lab_t'
DEV_MYSQL_DATABASE: 'com_path_imm_lab_t'

PROD_MYSQL_HOST: 'mysql09c.ahc.ufl.edu'
PROD_MYSQL_USERNAME: 'com_path_imm_lab_t'
PROD_MYSQL_DATABASE: 'com_path_imm_lab_t'


#SOURCE_HPC_MNT: '/blue/chamala/USER_NAME'
#SOURCE_PATHOLOGY_MNT: '/PATH$'

LOCAL_PATHOLOGY_MNT: '/ext/path'
LOCAL_HPC_MNT: '/ext/blue'

LINUX_PATHOLOGY_FASTQ_FOLDER: '/ext/path/DRL/Molecular/NGS/NextSeq_Fastq'
LINUX_ANALYSIS_OUT_FOLDER: '/ext/path/DRL/Molecular/NGS/GenomOncology/NextSeq'
GATOR_SEQ_SAMPLE_INPUT_FILE: '/ext/path/DRL/Molecular/NGS/GatorSeq/CODE_ENV/9_GS_Fastq_to_Analyze_V1_0.xlsx'
GATOR_PGX_SAMPLE_INPUT_FOLDER: '/ext/path/DRL/Molecular/Assays/PGX/PGX_Beaker_Interface'

LINUX_HPC_FASTQ_FOLDER: '/ext/blue/ufmolpath/share/GatorSeq_Share/GatorSeq_Fastq'

HPC_FASTQ_FOLDER: '/blue/ufmolpath/share/GatorSeq_Share/GatorSeq_Fastq'

LINUX_HPC_ANALYSIS_FOLDER: '/ext/blue/ufmolpath/share/GatorSeq_Share/GatorSeq_Analysis/CODE_ENV'
HPC_ANALYSIS_FOLDER: '~/GatorSeq_Share/GatorSeq_Analysis/CODE_ENV'
GATOR_SEQ_HPC_CODE_DIR: 'https://srikarchamala@bitbucket.org/srikarchamala/gatorseq_hpc_code'


MIRTH_GATORSEQ: '/ext/mirth_gatorseq/MIRTH_GATORSEQ'

HPC_NEXTFLOW_PROGRAM: 'module load singularity; ~/GatorSeq_Share/nextflow_versions/nextflow_v_19.07.0/nextflow '

GSBW_VERSION: '4.2.2'
NEXTFLOW_GIT_REPO: 'srikarchamala'

HPC_SFTP: 'path-svc-mol@sftp.rc.ufl.edu'
GATOR_SEQ_VERSION: '4.2'

#ILLUMINA BASESPACE APP SUBMISSION
ILLUMINA_BASESPACE_APP_SUBMISSION_INPUT_FILE: '/ext/path/DRL/Molecular/NGS/GatorSeq/CODE_ENV/Illumina_Basespace_App_Submission/Illumina_Basespace_App_Submission_V1.xlsx'
ILLUMINA_TABLE_NAME: 'illumina_basespace_run'

#COVID-19
COVID_19_TEST_INPUT_FOLDER: '/ext/path/DRL/Molecular/COVID19/COVID_19_QuantStudio/DevEnv/Results'
COVID_19_TEST_STATUS_FILE: '/ext/path/DRL/Molecular/COVID19/COVID_19_QuantStudio/DevEnv/COVID_19_EPIC_UPLOAD_LOG.xlsx' 
COVID_19_EPIC_UPLOAD_TABLE: 'COVID_19_EPIC_UPLOAD'

COVID_19_TEST_INPUT_FOLDER_PROD: '/ext/path/DRL/Molecular/COVID19/COVID_19_QuantStudio/ProdEnv/Results'
COVID_19_TEST_STATUS_FILE_PROD: '/ext/path/DRL/Molecular/COVID19/COVID_19_QuantStudio/ProdEnv/COVID_19_EPIC_UPLOAD_LOG.xlsx' 
COVID_19_TEST_SAMPLE_LOG: '/ext/path/DRL/Molecular/COVID19/COVID_19_QuantStudio/CODE_ENV/Results'
#COVID_19_TEST_SAMPLE_LOG: '/ext/path/DRL/Molecular/COVID19/COVID_19_QuantStudio/CODE_ENV/Results/RESULTS_OF'
COVID_19_EPIC_UPLOAD_TABLE_PROD: 'COVID_19_EPIC_UPLOAD_PROD'

#POOL_COVID-19
POOL_COVID_19_TEST_INPUT_FOLDER: '/ext/path/DRL/Molecular/COVID19/COVID_19_Pooled_Panther/CODE_ENV'

#TRUSIGHT
TRUSIGHT_APP_SUBMISSION_INPUT_FILE: '/ext/path/DRL/Molecular/NGS/GatorSeq/CODE_ENV/Illumina_Basespace_App_Submission/Trusight_App_Submission_V1.xlsx'
TRUSIGHT_TABLE_NAME: 'trusight_sample_run'
TRUSIGHT_TABLE_NAME_PROD: 'trusight_sample_run'
TRUSIGHT_CLI: '/home/s.majety/UFL_TruSight_Software_Suite_Beta/wgs-cli-1.19.0-beta.471.jar'
