#PATH_DRIVE_PASSWORD: 'XXXXXXXXX'
#HPC_DRIVE_PASSWORD: 'XXXXXXXXXX'
#
#NOTE: all variables should not have any space at the begining
#this will impact when calling in .sh scripts
#

CONFIG_TOKENS_FILE: 'config.tokens.yaml'
SOURCE_HPC_MNT: '/ufrc/chamala/USER_NAME'
SOURCE_PATHOLOGY_MNT: '/PATH$'

LOCAL_PATHOLOGY_MNT: '/ext/path'
LOCAL_HPC_MNT: '/ext/ufrc'

LINUX_PATHOLOGY_FASTQ_FOLDER: '/ext/path/DRL/Molecular/NGS/NextSeq_Fastq'
LINUX_ANALYSIS_OUT_FOLDER: '/ext/path/DRL/Molecular/NGS/GenomOncology/NextSeq'
GATOR_SEQ_SAMPLE_INPUT_FILE: '/ext/path/DRL/Molecular/NGS/GatorSeq/CODE_ENV/1_GS_Fastq_to_Analyze_V1_0.xlsx'
GATOR_PGX_SAMPLE_INPUT_FOLDER: '/ext/path/DRL/Molecular/Assays/PGX/PGX_Beaker_Interface'

LINUX_HPC_FASTQ_FOLDER: '/ext/ufrc/chamala/share/GatorSeq_Share/GatorSeq_Fastq'
#LINUX_HPC_ANALYSIS_FOLDER: '/ext/ufrc/chamala/share/GatorSeq_Share/GatorSeq_Analysis'

HPC_FASTQ_FOLDER: '/ufrc/chamala/share/GatorSeq_Share/GatorSeq_Fastq'

LINUX_HPC_ANALYSIS_FOLDER: '/ext/ufrc/chamala/share/GatorSeq_Share/CODE_ENV/gatorseq_hpc_code/analysis'
HPC_ANALYSIS_FOLDER: '/ufrc/chamala/share/GatorSeq_Share/CODE_ENV/gatorseq_hpc_code/analysis'
GATOR_SEQ_HPC_CODE_DIR: '/ufrc/chamala/share/GatorSeq_Share/CODE_ENV/gatorseq_hpc_code/next_flow'


MIRTH_GATORSEQ: '/ext/mirth_gatorseq/MIRTH_GATORSEQ'

HPC_NEXTFLOW_PROGRAM: 'module load nextflow/19.04.1; module load singularity/3.2.0; nextflow '

GSBW_VERSION: '3.0'

HPC_SFTP: 'path-svc-mol@sftp.rc.ufl.edu'
